/* -*- Mode: c++; c-basic-offset: 2; indent-tabs-mode: nil; tab-width: 40 -*- */
/* vim: set ts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIDOMEventTarget.idl"

interface nsIDOMDOMRequest;

[scriptable, builtinclass, uuid(c7bf50cc-1872-42bc-9242-f2816f69871e)]
interface nsIDOMBluetoothDevice : nsIDOMEventTarget
{
  readonly attribute DOMString address;
  readonly attribute DOMString name;
  readonly attribute DOMString icon;
  [binaryname(DeviceClass)] readonly attribute unsigned long class;
  [implicit_jscontext] readonly attribute jsval uuids;
  [implicit_jscontext] readonly attribute jsval services;
  readonly attribute bool connected;
  readonly attribute bool paired;
  [implicit_jscontext] attribute jsval onpropertychanged;
  [implicit_jscontext] attribute jsval onconnected;
  [implicit_jscontext] attribute jsval ondisconnected;

  nsIDOMDOMRequest connectHeadset();
  nsIDOMDOMRequest disconnectHeadset();
};
