/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/* Copyright © 2013, Deutsche Telekom, Inc. */

#include "nsISupports.idl"

[scriptable, uuid(999fa430-6180-11e1-b86c-0800200c9a66)]
interface nsINfcCallback : nsISupports
{
  /* Sets a callback to notifiy when NDEF Push message communication is available for use. */
  //[implicit_jscontext] boolean registerNDEFPushMessageCallback(
  //                               in nsINdefPushMessageCallback aCallback);
  /* Foreground dispatch allows the app, if in the foreground, to get routed all
     NFC messages. Useful for applications that write NFC tags. Privilaged API.
   */
  //[implicit_jscontext] boolean registerForegroundDispatch(
  //                               in nsIForegroundDispatchCallback aCallback);
};
