/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(999fa430-6180-11e1-b86c-0800200c9a66)]
interface nsINfcCallback : nsISupports
{
  void ndefDiscovered(in AString aNdefRecords);
  void ndefDisconnected(in AString aNfcHandle);

  void secureElementActivated(in AString aSEMessage);
  void secureElementDeactivated(in AString aSEMessage);
  void secureElementTransaction(in AString aSETransactionMessage);
};
