/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/* Copyright © 2013 Deutsche Telekom, Inc. */

#include "nsIDOMEventTarget.idl"
#include "nsIDOMDOMRequest.idl"

[scriptable, builtinclass, uuid(c2c01a50-4779-11e1-b86c-0800200c9a66)]
interface nsIDOMMozNfc : nsIDOMEventTarget {

  [implicit_jscontext]
  boolean validateNdefTag(in jsval records);

  /* Get metadata details of the discovered and connected NDEF message */
  [implicit_jscontext]
  nsIDOMDOMRequest ndefDetails();

  /**
   * NDEF Read returns an array of NDEF Records consisting of 1 or more elements
   */
  [implicit_jscontext]
  nsIDOMDOMRequest ndefRead();

  /* NDEF Write records that is an array of 1 or more records */
  [implicit_jscontext]
  nsIDOMDOMRequest ndefWrite(in jsval records);

  /* P2P Push NDEF records that is an array of 1 or more records */
  [implicit_jscontext]
  nsIDOMDOMRequest ndefPush(in jsval records);

  /* Permenantly makes the NFC NDEF tag read only */
  [implicit_jscontext]
  nsIDOMDOMRequest ndefMakeReadOnly();

  /**
   * NFCA functions
   */

  [implicit_jscontext]
  nsIDOMDOMRequest nfcATagDetails();

  [implicit_jscontext]
  nsIDOMDOMRequest nfcATagTransceive(in jsval params);

  [implicit_jscontext]
  nsIDOMDOMRequest connect(in unsigned long techType);

  [implicit_jscontext]
  nsIDOMDOMRequest close();
};
