/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

/* Copyright © 2013 Deutsche Telekom, Inc. */

#include "nsIDOMEvent.idl"

interface nsIDOMEvent;

[scriptable, builtinclass, uuid(41fcd640-4dd4-11e1-b86c-0800200c9a66)]
interface nsIDOMMozNfcEvent : nsIDOMEvent
{
  /**
   * NFC Tag message data
   */
  [implicit_jscontext]
  readonly attribute jsval message;
};
