/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIDOMEvent.idl"

[scriptable, builtinclass, uuid(41fcd640-4dd4-11e1-b86c-0800200c9a66)]
interface nsIDOMNfcNdefEvent : nsIDOMEvent
{
  /**
   * An NdefMessage is an array of NdefRecords.
   */
  [implicit_jscontext]
  readonly attribute jsval ndefMessages;
};
